default: &default
  adapter: postgresql
  encoding: unicode
  host: pharmacy_db
  username: kdan
  password: kdan

development:
  <<: *default
  database: pharmacy_development

test:
  <<: *default
  database: pharmacy_test

production:
  <<: *default
  database: pharmacy_production
